language: php
sudo: false

php:
    - 5.6
    - 7.0
    - hhvm
    - nightly

before_script:
    - travis_retry composer self-update
    - travis_retry composer install --no-interaction
    - travis_retry composer require satooshi/php-coveralls --dev

script:
    - mkdir -p coverage
    - phpunit

after_script:
    - travis_retry php vendor/bin/coveralls -v
